import { build } from "esbuild";
import { mkdirSync } from "node:fs";
import { resolve } from "node:path";

mkdirSync("dist", { recursive: true });

const kitDir = resolve("..", "kit", "src");

const common = {
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  // esbuild is a runtime dep (compile.ts uses it to transform .plan.tsx). Its
  // native binary lives in node_modules — keep it external so the lookup works.
  external: ["esbuild"],
  alias: {
    "@web-planner/kit": kitDir,
  },
  loader: { ".tsx": "tsx", ".ts": "ts" },
  jsx: "automatic",
  jsxImportSource: "preact",
  banner: { js: "// auto-generated by server/build.mjs — do not edit" },
  logLevel: "info",
};

await build({
  ...common,
  entryPoints: ["src/mcp.ts"],
  outfile: "dist/mcp.mjs",
});

await build({
  ...common,
  entryPoints: ["src/http-only.ts"],
  outfile: "dist/http-only.mjs",
});

console.log("built dist/mcp.mjs + dist/http-only.mjs");
